version: "3"

services:
    api:
        image: gaganvorn/password-generator
        ports:
            - 80:8000
        # volumes:
        #     - ./:/usr/src/app:ro
        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000  --reload