name: Test and Build

on: 
  push:
    branches:
      - "main"

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:

      - name: Pulling github repo
        uses: actions/checkout@v2
    
      - name: Install python version 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Update pip
        run: python -m pip install --upgrade pip
    
      - name: Install all dependencies
        run: pip install -r requirements.txt
    
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
        username: ${{ secret.DOCKER_HUB_USERNAME }}
        password: ${{ secret.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Build and push
          uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/password-generator:latest
